{% set name = "vmd" %}
{% set version = "1.9.3" %}
{% set sha256 = "5bdc314dc836d620fe510ed4b6c3dbe3cf66525b61680ffec4e2563cf495f128" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.ks.uiuc.edu/Research/vmd/vmd-1.9.3/files/final/vmd-{{ version }}.src.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win or linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - tk 8.5.*
    - xorg-libxi
    - libnetcdf
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
  run:
    - tk 8.5.*
    - xorg-libxi

test:
  commands:
    - vmd -h

about:
  home: https://www.ks.uiuc.edu/Research/vmd/
  license: LicenseRef-VMD
  license_file: LICENSE
  summary: 'Visual Molecular Dynamics'
  doc_url: https://www.ks.uiuc.edu/Research/vmd/vmd-{{ version }}/docs.html

extra:
  recipe-maintainers:
    - njzjz
    - RubenChM
