{% set name = "vmd" %}
{% set version = "1.9.3" %}
{% set sha256 = "9427a7acb1c7809525f70f635bceeb7eff8e7574e7e3565d6f71f3d6ce405a71" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.ks.uiuc.edu/Research/vmd/vmd-1.9.3/files/final/vmd-{{ version }}.bin.LINUXAMD64-CUDA8-OptiX4-OSPRay111p1.opengl.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win or osx]
  script:
    - export VMDINSTALLBINDIR=$PREFIX/bin
    - export VMDINSTALLLIBRARYDIR=$PREFIX/lib/vmd
    - ./configure LINUXAMD64
    - ./configure
    - cd src && make install
  overlinking_ignore_patterns:
    - "lib/vmd/*"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - {{ stdlib("c") }}
  host:
    - {{ cdt('mesa-libGL-devel') }}
    - xorg-libxi
    - xorg-libxinerama
  run:
    - xorg-libxi
    - xorg-libxinerama

test:
  commands:
    - vmd -h

about:
  home: https://www.ks.uiuc.edu/Research/vmd/
  license: VMD
  license_file: LICENSE
  summary: 'Visual Molecular Dynamics'
  doc_url: https://www.ks.uiuc.edu/Research/vmd/vmd-{{ version }}/docs.html

extra:
  recipe-maintainers:
    - njzjz
