context:
  name: vmd
  version: "1.9.3"
  
package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: http://www.ks.uiuc.edu/Research/vmd/vmd-1.9.3/files/final/vmd-${{ version }}.src.tar.gz
  sha256: 5bdc314dc836d620fe510ed4b6c3dbe3cf66525b61680ffec4e2563cf495f128

build:
  number: 3
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
    - tk 8.5.*
    - xorg-libxi
    - libnetcdf
    - ${{ cdt('xorg-x11-proto-devel') }}
    - ${{ cdt('libx11-devel') }}
    - if: osx
      then:
      - libcxx-devel 16.*
      - fltk
  run:
    - tk 8.5.*
    - xorg-libxi

tests:
  - script:
    - vmd -h

about:
  homepage: https://www.ks.uiuc.edu/Research/vmd/
  license: LicenseRef-VMD
  license_file: LICENSE
  summary: 'Visual Molecular Dynamics'
  documentation: https://www.ks.uiuc.edu/Research/vmd/vmd-${{ version }}/docs.html

extra:
  recipe-maintainers:
    - njzjz
    - RubenChM
