azure:
  free_disk_space: true
  store_build_artifacts: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
build_platform:
  linux_64: linux_64
  osx_64: osx_64
conda_build_tool: rattler-build