travis:
  secure:
    BINSTAR_TOKEN: LVA6x+KoXlCjpFRi7L9Ap8N7+QRo9oUblQWWUc5puEZMKKJZL0mbO8bE/Wy9KzWGaVoEw4zg1s1ZebecyOmpAVhcmrzK9Inv2ABIxixf6yhCdVVtM0hpYhuApqG1T8jEs4n9EDBqYbGcNUsFBcVs9r0W985T2Whc9xP6ZE9f7mbzw05C0OTXErtPp/7EOdG1JFRkApPSWOvquDX0TnbsnTPIii4q7rZIZkUb8c+GtYCfJ0hg25lNKRVE+KYeOZABp8ZdAVBoI1L0fRB0qRLFheS4xOdgZDXJeOg7sLKsI5BE4auVn5EFIP8nPRdV3iIGcBMkcg60j4qpkf1v8xc0TJ37V0Eo42uV0PvQ7dJaYD5K1u22PV+1tsSDfq4vqIYoBuYcW9STVWNpB+d3yAfsOxOINQih+J1iIr3AVYNiC0Gl70OzAj/DjPyO0Vt0gLt7PP58tKdrwUHmEvbHTrEPB/JFfV04wmkGbBGq9PGYRlgtPCWedpHRzdkNJEf43ICWN6E7apVTDF2fxNq8gCltVS00mIQucJV6LFHlYhP1mv5Fs3Blf0X1X8EihmHYA18o+MqDETxNP30qeLqUHqqIjM7oBSTKyn+ql0cPJZ06sck7hC7b0XHQsddN8lG8IQG/ApS9bUMqTAbrqOr6EuPRfugTbOgJEhRbrEylWzoCHFI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
